# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fps-zxkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fps-zxkit
	pod 'ZXKitCore', '~> 2.0.0'
	pod 'ZXKitFPS', '~> 2.0.0'
end
