# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDKitSwift_FPS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDKitSwift_FPS
	pod 'DDKitSwift/core', '~> 3'
	pod 'DDKitFPS', '~> 3'
end
